### ISSUE TITLE
[주간회의] 11월 30일, 12월 7일

### ISSUE THREAD

**Issue by kangdain** [kangdain/youtuboard#24]
### 한 일

-  제 11 차 TLO 교육  - 블록체인 및 이더리움 플랫폼 소개 및 실습 (월)

-  구독자현황 통계를 보여주는 그래프를 임의의 사진을 가져와 화면에 넣고, 컨텐츠가 수평정렬이 되난 수직으로 가운데 정렬이 되지 않는 이슈 발생 및  해결(화)

- 채용공고 확인 및 희망 회사 조사 (수)

- 구독자 정보를 확인 하는 레이아웃을 만들기 위해 부트스트랩 panel view를 이용하여 화면을 구성.(목)	

- 구독자의 댓글을 확인 하는 comment view 완성 (금) 

### 할일 

 - 나머지 레이아웃 만들기 (setting, search etc ..)

### 한 일

-  제 11 차 TLO 교육  - 블록체인 및 이더리움 플랫폼 소개 및 실습 (월)

-  history data 뷰를 완성하여 구독자의 유입 유출 정보를 파악 한다. (화)

-search 화며을 구성하여 원하는 정보를 찾을 수 있도록 만드는 과정에서 홈 상단에 위치 시키도록 할때 화면이 작아질 경우 레이아웃이 틀어지는 이슈 발생(수)
- settings view 를 통해 사용자가 원하는 테마를 선택하여 사용할 수 있다.(목)
	
- mytask view를 만들어 등록한 컨텐츠를 관리할 수 있다. (금) 

### 할일 

화면간 데이터 통신을 위해 vuex 및 youtube data api 사용

**Comment by unizard** [comment]
@kangdain 간단한 결과 화면 캡춰 이런거 없나요?
